apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pods-clusterrole
  namespace: demo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumes
  verbs:
  - get
  - list
  - watch