apiVersion: v1
data:
  myserver-gzip.cfg: |
    gzip on;
    gzip_comp_level 5;
    gzip_proxied     expired no-cache no-store private auth;
    gzip_types text/plain text/css application/xml text/javascript;
  myserver-status.cfg: |
    location /nginx-status {
        stub_status on;
        access_log off;
    }
  myserver.conf: "server {\n    listen 443 ssl;\n    server_name www.ik8s.io;\n\n
    \   ssl_certificate /etc/nginx/certs/tls.crt; \n    ssl_certificate_key /etc/nginx/certs/tls.key;\n\n
    \   ssl_session_timeout 5m;\n\n    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; \n\n    ssl_ciphers
    ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE; \n    ssl_prefer_server_ciphers
    on;\n\n    include /etc/nginx/conf.d/myserver-*.cfg;\n\n    location / {\n        root
    /usr/share/nginx/html;\n    }\n}\n\nserver {\n    listen 80;\n    server_name
    www.ilinux.io; \n    return 301 https://$host$request_uri; \n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-sslvhosts-confs